apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx-minikube:latest  # Image built locally and used in Minikube
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: "2"         # CPU limit: 2 vCPUs
              memory: "256Mi"  # Memory limit: 256MB
            requests:
              cpu: "1"         # Minimum CPU request: 1 vCPU
              memory: "128Mi"  # Minimum Memory request: 128MB
