apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-minikube.fullname" . }}
  labels:
    {{- include "nginx-minikube.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    {{- include "nginx-minikube.selectorLabels" . | nindent 4 }}
