apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-minikube
spec:
  project: default
  source:
    repoURL: 'https://github.com/GiliFaibish1999/nginx-minikube'
    targetRevision: main
    path: helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true