name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          kubernetes-version: v1.27.0
          addons: ingress, registry,  metrics-server

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Install NGINX Ingress Controller with Helm
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
          kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx

      - name: Set up Helm CLI
        uses: azure/setup-helm@v3
        
      - name: Build Docker Image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build -t nginx-minikube:latest ./nginx/
          minikube image load nginx-minikube:latest

      - name: Deploy with Helm
        run: |
          helm upgrade --install nginx-release ./helm-chart/ \
            --set image.repository=nginx-minikube,image.tag=latest,resources.limits.memory=256Mi,resources.limits.cpu=200m --wait

      - name: Apply ArgoCD Application
        run: |
          kubectl apply -f argocd/app.yaml