name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Kind Cluster
        uses: helm/kind-action@v1
        with:
          version: v0.20.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          kubernetes-version: v1.27.0
          addons: ingress

      - name: Set up Helm CLI
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Build Docker Image
        run: |
          eval $(minikube docker-env)
          docker build -t nginx-minikube:latest ./nginx/
          kind load docker-image nginx-minikube:latest

      - name: Deploy with Helm
        uses: helm/kubectl-helm@v1
        with:
          command: upgrade --install nginx-release ./helm-chart/ \
            --set image.repository=nginx-minikube \
            --set image.tag=latest \
            --namespace default \
            --wait

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc

      # - name: Publish Helm Chart
      #   uses: stefanprodan/helm-push-action@main
      #   with:
      #     chart: ./helm-chart/
      #     repo: gh-pages
      #     token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up ArgoCD
        uses: cloudposse/github-action-deploy-argocd@main
        with:
          cluster: https://kubernetes.default.svc
          toolchain: helm
          environment: production
          namespace: default
          application: nginx-minikube
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          image: nginx-minikube
          image-tag: latest
          operation: deploy
          debug: false
          synchronously: true
