name: CI/CD Nginx Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube addons enable ingress

      - name: Build Docker Image
        run: |
          eval $(minikube docker-env)
          docker build -t localhost:5000/nginx-minikube:latest ./nginx

      - name: Push to Local Registry
        run: |
          docker tag localhost:5000/nginx-minikube:latest localhost:5000/nginx-minikube:latest
          docker push localhost:5000/nginx-minikube:latest

      - name: Deploy to Minikube with Helm
        run: |
          helm upgrade --install nginx-app ./helm-chart --namespace default

      - name: Apply ArgoCD App
        run: kubectl apply -f argocd/app.yaml
