name: CD
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nginx-app
  REGISTRY: localhost:5000  # Fake registry inside Minikube

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          kubernetes-version: v1.27.0
          addons: registry,ingress  # Enable built-in Minikube registry

      - name: Wait for Minikube Registry to Start
        run: |
          sleep 5  # Give Minikube registry time to initialize
          kubectl get pods -n kube-system | grep registry

      - name: Ensure Minikube Registry is Running
        run: |
          kubectl port-forward --namespace kube-system service/registry 5000:80 &

      - name: Configure Minikube Docker
        run: |
          eval $(minikube -p minikube docker-env) # Ensure Minikube environment is used

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} ./nginx/

      - name: Load Image into Minikube
        run: |
          minikube image load ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Verify Image in Minikube
        run: |
          minikube image list | grep ${{ env.IMAGE_NAME }}

      - name: Update `values.yaml` with New Image Tag
        run: |
          cd ./nginx-app
          # Update image tag in values.yaml
          sed -i "s|image.tag:.*|image.tag: '${{ github.sha }}'|" values.yaml
          # Check if the file actually changed
          if git diff --quiet values.yaml; then
            echo "No changes in values.yaml, skipping commit."
            exit 0
          fi
          # Configure Git
          git config --global user.name 'GiliFaibish1999'
          git config --global user.email 'gilifaibishpro@gmail.com'
          # Commit and push only if there are changes
          git add values.yaml
          git commit -m "Update values.yaml with new image tag"
          git push

      - name: Install Helm CLI
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Deploy to Minikube using Helm
        run: |
          helm upgrade --install nginx-app ./nginx-app \
            --set image.repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
            --set image.tag=${{ github.sha }} \
            --set image.pullPolicy=IfNotPresent

      - name: Force Pod Restart
        run: |
          kubectl rollout restart deployment/nginx-app

      - name: Verify Deployment Rollout
        run: |
          kubectl rollout status deployment/nginx-app --timeout=60s
          kubectl get pods -o wide
          kubectl get svc

      - name: Show Pod Logs if Deployment Fails
        if: failure()
        run: |
          kubectl get pods -o wide
          kubectl describe pod -l app=nginx-app
          kubectl logs -l app=nginx-app
